### ISSUE TITLE
控制面板中文乱码

### ISSUE THREAD

**Issue by HasonHuang** [PerccyKing/batslog#1]
# 期望
1. 控制面板的选项卡显示中文：控制台、设置。
2. 输出的中文内容正确显示。

# 实际
1. 选项卡文字乱码。
2. 控制面板输出的中文乱码。

# 环境
- IDEA 版本：2020.2.3
- Batslog 版本：20.11.15.1902-Release

**Comment by PerccyKing** [comment]
尝试一下改一下配置文件呢，https://www.cnblogs.com/lwcode6/p/11598632.html

**Comment by PerccyKing** [comment]
![image](https://user-images.githubusercontent.com/59950759/100583498-b9dce480-3325-11eb-8d68-8fc746fd69e6.png)

**Comment by HasonHuang** [comment]
已解决。
修改 IDEA `idea64.exe.vmoptions` 文件，添加：
```
-Dfile.encoding=UTF-8
```
