### ISSUE TITLE
SQL显示中文乱码

### ISSUE THREAD

**Issue by A6083450** [PerccyKing/batslog#11]
输出的SQL中参数有中文，格式化显示时出现乱码
![image](https://user-images.githubusercontent.com/34879801/117910005-c1a9a780-b30d-11eb-88e9-518ca2758a30.png)

**Comment by PerccyKing** [comment]
你好，请尝试一下这种方式，看看能不能行呢 #7

**Comment by A6083450** [comment]
好的，谢谢，手动复制不会乱码，只是自动打印sql输出中文就会，我的控制台编码是UTF-8

**Comment by PerccyKing** [comment]
这个我后期再优化一下
