### ISSUE TITLE
希望能在每条 sql 语句之后增加分号

### ISSUE THREAD

**Issue by b19g3r** [PerccyKing/batslog#13]
希望能在每条 sql 语句之后增加分号

**Comment by PerccyKing** [comment]
好的，这个已经做了，下个版本发布，感谢你的反馈

**Comment by PerccyKing** [comment]
你好，功能已经在 [21.05.27.2253](https://github.com/PerccyKing/batslog/releases/tag/21.05.27.2253) 发布，你可以等待jetbrain应用商店上架后升级使用，也可以直接下载，抢先使用，感谢你的支持 [点击下载](https://github.com/PerccyKing/batslog/releases/download/21.05.27.2253/batslog-21.05.27.2253-RE.zip)
