### ISSUE TITLE
是否可以支持序号

### ISSUE THREAD

**Issue by PengFei-io** [PerccyKing/batslog#15]
1.支持面板上有sql的编号。方便查看
2.不同的sql类型显示不同颜色，例如写操作红色，查询操作蓝色

**Comment by PerccyKing** [comment]
可以的，这个功能已经纳入下一个版本归还，感谢你的反馈

**Comment by PerccyKing** [comment]
你好，功能已经在 [21.07.04.1838](https://github.com/PerccyKing/batslog/releases/tag/21.07.04.1838) 发布，你可以等待jetbrain应用商店上架后升级使用，也可以直接下载，抢先使用，感谢你的支持与持续关注 [点击下载](https://github.com/PerccyKing/batslog/releases/download/21.07.04.1838/batslog-21.07.04.1838-RE.zip)

**Comment by PengFei-io** [comment]
> 可以的，这个功能已经纳入下一个版本归还，感谢你的反馈

谢谢，已经更新上去了，很棒，支持。好评
