### ISSUE TITLE
执行sql的时间

### ISSUE THREAD

**Issue by PengFei-io** [PerccyKing/batslog#16]
是否可以在下一版本支持执行sql的时间，例如什么时候开始执行的，什么时候结束的，用了多长时间
这样方便知道是什么时候执行的这条sql，也方便定位错误

**Comment by PerccyKing** [comment]
你好，因为本插件是非侵入性的，插件的原理在于解析idea 控制台打印的SQL日志，所以SQL的执行时间 插件是获取不到的，非常抱歉，这个功能不能实现，感谢你的反馈

**Comment by PengFei-io** [comment]
那能不能打印sql的同时把操作系统当前时间打印出来呢。这样和具体执行sql的时间其实是差不多的，也是可以的

**Comment by PengFei-io** [comment]
> 你好，因为本插件是非侵入性的，插件的原理在于解析idea 控制台打印的SQL日志，所以SQL的执行时间 插件是获取不到的，非常抱歉，这个功能不能实现，感谢你的反馈

那能不能打印sql的同时把操作系统当前时间打印出来呢。这样和具体执行sql的时间其实是差不多的，也是可以的

**Comment by PerccyKing** [comment]
> > 你好，因为本插件是非侵入性的，插件的原理在于解析idea 控制台打印的SQL日志，所以SQL的执行时间 插件是获取不到的，非常抱歉，这个功能不能实现，感谢你的反馈
> 
> 那能不能打印sql的同时把操作系统当前时间打印出来呢。这样和具体执行sql的时间其实是差不多的，也是可以的

需要SQL执行时间的话，建议配置系统的日志，同步打印时间，这个时间是相对准确的，batslog在解析日志的时候是会解析到的，你的建议我也会考虑在下个版本进行更新，感谢你的反馈

eg:
`
日志
2021-07-07 11:26:36.395 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query  : ==>  Preparing: SELECT * FROM role 
2021-07-07 11:26:36.396 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query  : ==> Parameters: (String)

BatsLog 输出

-- --------------------------------------
# 0001 2021-07-07 11:26:36.395 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query  : ==>  
select *
from role;

`
![image](https://user-images.githubusercontent.com/59950759/124699820-281e0100-df1e-11eb-95e9-efdd38270849.png)

**Comment by PengFei-io** [comment]
> > > 你好，因为本插件是非侵入性的，插件的原理在于解析idea 控制台打印的SQL日志，所以SQL的执行时间 插件是获取不到的，非常抱歉，这个功能不能实现，感谢你的反馈
> > 
> > 
> > 那能不能打印sql的同时把操作系统当前时间打印出来呢。这样和具体执行sql的时间其实是差不多的，也是可以的
> 
> 需要SQL执行时间的话，建议配置系统的日志，同步打印时间，这个时间是相对准确的，batslog在解析日志的时候是会解析到的，你的建议我也会考虑在下个版本进行更新，感谢你的反馈
> 
> eg:
> `
> 日志
> 2021-07-07 11:26:36.395 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query : ==> Preparing: SELECT * FROM role
> 2021-07-07 11:26:36.396 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query : ==> Parameters: (String)
> 
> BatsLog 输出
> 
> 0001 2021-07-07 11:26:36.395 DEBUG 6 --- [nio-8080-exec-3] c.c.w.mapper.X.query : ==>
> select *
> from role;
> `
> ![image](https://user-images.githubusercontent.com/59950759/124699820-281e0100-df1e-11eb-95e9-efdd38270849.png)

已经做得很好了，感谢
