### ISSUE TITLE
监听到的SQL当中表名不正确

### ISSUE THREAD

**Issue by BNTang** [PerccyKing/batslog#19]

**Comment by PerccyKing** [comment]
你好，感谢你的反馈：
1.麻烦提供一下错误截图
2.麻烦检查一下是否开启脱敏配置
![image](https://user-images.githubusercontent.com/59950759/129820307-1883abc3-8a5c-427c-ba8b-3324ca11142d.png)
3.麻烦看一下idea中是否有BatsLog相关的错误日志
 感谢你的支持

**Comment by BNTang** [comment]
ok，是我开了脱敏
