### ISSUE TITLE
[建议] 新增格式化外部 SQL 语句

### ISSUE THREAD

**Issue by HasonHuang** [PerccyKing/batslog#2]
## 需求

格式化外部 SQL 语句。

场景：在开发环境日志（远程服务器）中打印了 SQL 语句，无法使用 Batslog 格式化语句，只能手动替换。

**Comment by PerccyKing** [comment]
收到！我这边尽快发版

**Comment by PerccyKing** [comment]
新功能已经在【20.12.13.1659】 发布   https://github.com/PerccyKing/batslog/releases/tag/20.12.13.1659
