### ISSUE TITLE
解析SQL错误

### ISSUE THREAD

**Issue by CCnevergiveup** [PerccyKing/batslog#24]
有个BUG。解析出来的SQL是错的

示例如下： ==> Preparing: select * from user u where INSTR(?,u.name) ==> Parameters: jack,tom(String)

解析结果: select * from user u where INSTR(jack,u.name)

参数中有','的时候 就出现问题了

**Comment by PerccyKing** [comment]
是的，存在这种问题的，后期会在算法上优化，先记录了，感谢你的反馈，最近有些忙，回复消息不太及时
