### ISSUE TITLE
关于配置中 控制台颜色 希望可以设置背景颜色为空 或者可以手动更改json文档

### ISSUE THREAD

**Issue by Forgotten-wm** [PerccyKing/batslog#27]

**Comment by PerccyKing** [comment]
> 

你好，我没有太明白你的意思，能详细的描述一下吗？
如果是不想要背景颜色的话，可以在颜色配置里面将是否启用关闭，或者删除配置文件
JSON是用来快速辅助配置的，也是可以编辑的

**Comment by Forgotten-wm** [comment]
[
    {
        "keyword": "INSERT",
        "enabled": true,
        "fg": "#EE1414"
    },
    {
        "keyword": "UPDATE",
        "enabled": true,
        "fg": "#FFFFFF"
    },
    {
        "keyword": "DELETE",
        "enabled": true,
        "fg": "#FFFFFF"
    }
]

**Comment by PerccyKing** [comment]
> [
>     {
>         "keyword": "INSERT",
>         "enabled": true,
>         "fg": "#EE1414"
>     },
>     {
>         "keyword": "UPDATE",
>         "enabled": true,
>         "fg": "#FFFFFF"
>     },
>     {
>         "keyword": "DELETE",
>         "enabled": true,
>         "fg": "#FFFFFF"
>     }
> ]

你好，我明白了，你是想只保留前景色，这个后面我会进行适配的，感谢你的反馈
