### ISSUE TITLE
mac版本idea安装启动无效果

### ISSUE THREAD

**Issue by PengFei-io** [PerccyKing/batslog#28]
![image](https://user-images.githubusercontent.com/55048787/156916769-e7326ab6-06ff-4cf2-a3f2-1096ee50f599.png)

**Comment by PerccyKing** [comment]
> ![image](https://user-images.githubusercontent.com/55048787/156916769-e7326ab6-06ff-4cf2-a3f2-1096ee50f599.png)
> 

你好，除了自动监听功能异常之外，其他功能可以正常使用吗？

**Comment by PengFei-io** [comment]
其他的都可以。感谢关注



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月06日 17:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PerccyKing/batslog] mac版本idea安装启动无效果 (Issue #28) |

你好，除了自动监听功能异常之外，其他功能可以正常使用吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PerccyKing** [comment]
> 其他的都可以。感谢关注
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2022年03月06日 17:43 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.******@***.***> |
> | 主题 | Re: [PerccyKing/batslog] mac版本idea安装启动无效果 (Issue #28) |
> 
> 你好，除了自动监听功能异常之外，其他功能可以正常使用吗？
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，麻烦告诉我一下你的idea版本，Mac OS版本呢，我在10.13版本的Mac OS上没能复现

**Comment by PengFei-io** [comment]
idea版本: 2020.1
Mac os: MacBook Air (13-inch, Early 2015)
也许是我使用的mac比较旧了导致的，我同事的就没问题。我的另外一台电脑也是可以的。
我觉得可以忽略它的错误了。目前使用起来还是很不错的。感谢回复。



在 2022-03-07 15:10:41，"PerccyKing" ***@***.***> 写道：

其他的都可以。感谢关注

---- 回复的原邮件 ----
| 发件人 | @.> |
| 日期 | 2022年03月06日 17:43 |
| 收件人 | @.> |
| 抄送至 | @.@.> |
| 主题 | Re: [PerccyKing/batslog] mac版本idea安装启动无效果 (Issue #28) |

你好，除了自动监听功能异常之外，其他功能可以正常使用吗？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: @.***>

你好，麻烦告诉我一下你的idea版本，Mac OS版本呢，我在10.13版本的Mac OS上没能复现

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
