### ISSUE TITLE
自动监听功能无效

### ISSUE THREAD

**Issue by PengFei-io** [PerccyKing/batslog#30]
![image](https://user-images.githubusercontent.com/55048787/165727593-233f3fb9-c568-4b08-b467-f7da2be3fb10.png)
以上是sql日志

![image](https://user-images.githubusercontent.com/55048787/165727629-3afe2128-34a2-4bd1-8a29-5ecda49af4d9.png)
以上是监听启动，没有日志输出。
这个功能我以前还能用，但是现在就不能用了。不清楚是什么原因。
还希望大神帮忙查看
操作系统: windows

**Comment by PengFei-io** [comment]
idea版本: 2019.2.4

**Comment by PengFei-io** [comment]
![image](https://user-images.githubusercontent.com/55048787/165727833-72103ddb-0d29-47f1-8292-a05b0b132297.png)

**Comment by PerccyKing** [comment]
是突然就失效了吗？

**Comment by PengFei-io** [comment]
是的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月28日 17:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [PerccyKing/batslog] 自动监听功能无效 (Issue #30) |

是突然就失效了吗？

**Comment by PerccyKing** [comment]
> 是的
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2022年04月28日 17:58 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.******@***.***> |
> | 主题 | Re: [PerccyKing/batslog] 自动监听功能无效 (Issue #30) |
> 
> 是突然就失效了吗？
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

建议，重装试一下呢😂😂
