### ISSUE TITLE
解析失败

### ISSUE THREAD

**Issue by yueyangyang** [PerccyKing/batslog#34]
`- ==>  Preparing: SELECT dictGet('default.DICT_THREEE_TYPE','EVENT_TYPE',toUInt64(EVENT_THREE_TYPE)) AS eventThreeTypeDesc,EVENT_THREE_TYPE AS eventThreeType, count(1) as num from default.CK_ALARM_MERGE_ALL t GLOBAL LEFT JOIN default.CK_ALARM_MERGE_HANDLE a ON t.UU_ID = a.UU_ID WHERE t.CREATE_TIME >= toDateTime(?) and t.CREATE_TIME < toDateTime(?) and has(multiSearchAllPositions(TAGS, [ ? ] ),0)=0 AND t.TENANT_ID = ? AND EVENT_THREE_TYPE IS NOT NULL and a.ALARM_TIME >= toDateTime(?) and a.ALARM_TIME < toDateTime(?) group by EVENT_THREE_TYPE order by num desc limit ? 
14:01:35.785 [XNIO-2 task-1] DEBUG ssa.web.standard.alarm.mapper.AlarmInfoNewMapper.getBaseByFieldList - ==> Parameters: 2022-08-08 11:00:00.0(Timestamp), 2022-08-15 11:00:00.0(Timestamp), 恶意代码(String), -1(Long), 2022-08-08 11:00:00.0(Timestamp), 2022-08-15 11:00:00.0(Timestamp), 5(Integer)`
这一段解析出来是
`SELECT dictGet('default.DICT_THREEE_TYPE','EVENT_TYPE',toUInt64(EVENT_THREE_TYPE)) AS eventThreeTypeDesc,EVENT_THREE_TYPE AS eventThreeType, count(1) as num from default.CK_ALARM_MERGE_ALL t GLOBAL LEFT JOIN default.CK_ALARM_MERGE_HANDLE a ON t.UU_ID = a.UU_ID WHERE t.CREATE_TIME >= toDateTime(?) and t.CREATE_TIME < toDateTime(?) and has(multiSearchAllPositions(TAGS, [ ? ] ),0)=0 AND t.TENANT_ID = ? AND EVENT_THREE_TYPE IS NOT NULL and a.ALARM_TIME >= toDateTime(?) and a.ALARM_TIME < toDateTime(?) group by EVENT_THREE_TYPE order by num desc limit ? ;`
没把参数值填充进去。

**Comment by PerccyKing** [comment]
稍等，我检查一下

**Comment by PerccyKing** [comment]
你好，问题已经找到了，目前batslog对你使用的数据库，支持不是太好（部分函数和关键字不能识别），我后面会优化的

**Comment by PerccyKing** [comment]
[batslog-22.08.27.1840-2019.2-TE.zip](https://github.com/PerccyKing/batslog/files/9437780/batslog-22.08.27.1840-2019.2-TE.zip)
你好，如果你空的话，麻烦尝试yi一下这个版本，这个版本添加了对clickhouse的支持，需要在设置里面选择一下
