### ISSUE TITLE
idea版本 2021.3.3

### ISSUE THREAD

**Issue by We41w4e** [PerccyKing/batslog#35]
![image](https://user-images.githubusercontent.com/111553542/198234350-f5d2b91a-cc96-4fee-a167-67cc67a202d9.png)

**Comment by PerccyKing** [comment]
你好，最迟下周一能适配

**Comment by PerccyKing** [comment]
你好，不好意思，能否提供一下格式化的日志呢，脱敏的也可以

**Comment by sdhzwc** [comment]
> 你好，不好意思，能否提供一下格式化的日志呢，脱敏的也可以

这个不是在格式化的时候报错，是在不知觉的情况，事件日志看到的

**Comment by PerccyKing** [comment]
这个可能是对某些日志解析失败了，例如参数行没有数据类型，或者参数行中参数有逗号，这个都会影响到batslog的解析
