### ISSUE TITLE
菜单乱码问题

### ISSUE THREAD

**Issue by wangweiping** [PerccyKing/batslog#4]
![image](https://user-images.githubusercontent.com/18497716/103134136-f2d06500-46e9-11eb-8bbf-2ab00439307d.png)

这些地方都是乱码

**Comment by PerccyKing** [comment]
建议参照一下这个配置一下呢

https://www.cnblogs.com/lwcode6/p/11598632.html

**Comment by wangweiping** [comment]
谢谢，可以了

**Comment by PerccyKing** [comment]
> 谢谢，可以了

不客气
