### ISSUE TITLE
插件在idea 2023.1.2 版本中显示的问题

### ISSUE THREAD

**Issue by yangsuys** [PerccyKing/batslog#45]
我不知道我的idea是哪里的设置有问题,还是插件有问题. 在我的不同项目中,有的在侧边栏可以显示插件图标.有的显示不了. 将插件卸载后,再次安装还是这样. 
![no](https://github.com/PerccyKing/batslog/assets/59553866/e1137017-1c56-4ff8-803f-14afaace48c5)
![yes](https://github.com/PerccyKing/batslog/assets/59553866/249f4003-936f-438f-a288-2fbb3dc98552)

**Comment by PerccyKing** [comment]
![image](https://github.com/PerccyKing/batslog/assets/59950759/5bb5bc5c-af5a-4bba-bf41-be405fe6c256)
右侧没有显示的话，点击左侧的三个点，看看能不能找到呢

**Comment by yangsuys** [comment]
可以了,谢谢

**Comment by PerccyKing** [comment]
不客气的
