### ISSUE TITLE
出现参数解析时  NumberFormatException

### ISSUE THREAD

**Issue by fish-kings** [PerccyKing/batslog#47]
具体错误如下
insert into ae_dic_event_level (event_level,branch_id,event_level_name, total_deal_time_limit, assign_deal_time_limit, analyze_deal_time_limit, audit_deal_time_limit, `state`, ord, modify_empid, modify_time,inputcode1,inputcode2,remark) values (?, ?,?,?, ?, ?, ?, ?, ?, ?, ?,?,?,?)	 5(String), 120161(Integer), null, 20(Short), 5(Short), 10(Short), 5(Short), null, null, 1072(Integer), 2023-07-26T13:03:34.860061(LocalDateTime), hjkjhk(String), hj(String), hkhj(String)	23/07/26 13:03:35
         java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
         java.base/java.lang.Integer.parseInt(Integer.java:668)
         java.base/java.lang.Short.parseShort(Short.java:137)
         java.base/java.lang.Short.valueOf(Short.java:193)
         java.base/java.lang.Short.valueOf(Short.java:219)
         cn.com.pism.batslog.util.SqlFormatUtil.pack(SqlFormatUtil.java:569)
         cn.com.pism.batslog.util.SqlFormatUtil.parseParamToList(SqlFormatUtil.java:536)
         cn.com.pism.batslog.util.SqlFormatUtil.print(SqlFormatUtil.java:312)
         cn.com.pism.batslog.util.SqlFormatUtil.format(SqlFormatUtil.java:122)
         cn.com.pism.batslog.util.SqlFormatUtil.format(SqlFormatUtil.java:80)
         cn.com.pism.batslog.util.SqlFormatUtil.format(SqlFormatUtil.java:50)
         cn.com.pism.batslog.points.BatsLogConsoleFolding.notEnabledMultiSqlPrefix(BatsLogConsoleFolding.java:80)
         cn.com.pism.batslog.points.BatsLogConsoleFolding.shouldFoldLine(BatsLogConsoleFolding.java:46)
         com.intellij.execution.impl.ConsoleViewImpl.foldingForLine(ConsoleViewImpl.java:1117)
         com.intellij.execution.impl.ConsoleViewImpl.lambda$updateFoldings$17(ConsoleViewImpl.java:1060)
         com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:291)
         com.intellij.openapi.editor.impl.FoldingModelImpl.runBatchFoldingOperation(FoldingModelImpl.java:232)
         com.intellij.openapi.editor.FoldingModel.runBatchFoldingOperation(FoldingModel.java:96)
         com.intellij.execution.impl.ConsoleViewImpl.updateFoldings(ConsoleViewImpl.java:1020)
         com.intellij.execution.impl.ConsoleViewImpl.highlightHyperlinksAndFoldings(ConsoleViewImpl.java:963)
         com.intellij.execution.impl.ConsoleViewImpl.flushDeferredText(ConsoleViewImpl.java:753)
         com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.doRun(ConsoleViewImpl.java:1577)
         com.intellij.execution.impl.ConsoleViewImpl$FlushRunnable.run(ConsoleViewImpl.java:1573)
         com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
         com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
         com.intellij.util.Alarm$Request.run(Alarm.java:354)
         java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
         java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
         com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
         com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
         com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
         com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
         com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
         com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
         java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
         java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
 建议在一下代码中增加空指针判断
<img width="810" alt="image" src="https://github.com/PerccyKing/batslog/assets/67667211/d4fe2364-9b8a-40e2-94b0-3c1f4ded3670">

**Comment by PerccyKing** [comment]
嗯，我处理一下

**Comment by PerccyKing** [comment]
这里已经进行了优化，试一下这个版本呢
[batslog-23.07.26.1527-RE.zip](https://github.com/PerccyKing/batslog/files/12169223/batslog-23.07.26.1527-RE.zip)

**Comment by fish-kings** [comment]
好的
