### ISSUE TITLE
控制台复制SQL参数错误

### ISSUE THREAD

**Issue by hopana** [PerccyKing/batslog#53]
### 控制台输出日志如下：
23-11-07 09:42:48 DEBUG o.c.b.e.i.p.e.E.selectProcessInstanceByQueryCriteria:135 xYKjpmPr ==>  Preparing: select distinct RES.* from ACT_RU_EXECUTION RES inner join ACT_RE_PROCDEF P on RES.PROC_DEF_ID_ = P.ID_ WHERE ( RES.PARENT_ID_ is null ) order by RES.ID_ asc LIMIT ? OFFSET ?
23-11-07 09:42:48 DEBUG o.c.b.e.i.p.e.E.selectProcessInstanceByQueryCriteria:135 xYKjpmPr ==> Parameters: 2147483647(Integer), 0(Integer)
23-11-07 09:42:48 DEBUG o.c.b.e.i.p.e.E.selectProcessInstanceByQueryCriteria:135 xYKjpmPr <==      Total: 54
### 复制后的SQL
select distinct RES.*
from ACT_RU_EXECUTION RES
	inner join ACT_RE_PROCDEF P on RES.PROC_DEF_ID_ = P.ID_
where RES.PARENT_ID_ is null
order by RES.ID_ asc
limit '0', 2147483647;

其中，limit后的参数应该是 limit 0 , 2147483647；而不是 limit '0', 2147483647

**Comment by PerccyKing** [comment]
收到，我修复一下

**Comment by hopana** [comment]
thanks
