### ISSUE TITLE
参数类型转换错误

### ISSUE THREAD

**Issue by qingdengyideng** [PerccyKing/batslog#6]
long类型的参数也会当成字符串转换
![image](https://user-images.githubusercontent.com/26715233/104430521-be054e80-55c1-11eb-97f9-99f62050e308.png)

**Comment by PerccyKing** [comment]
问题收到，将在下个版本解决

**Comment by PerccyKing** [comment]
问题已经修复，请下载 https://github.com/PerccyKing/batslog/releases/download/21.01.13.2217/batslog-21.01.13.2217-Release.zip

**Comment by qingdengyideng** [comment]
可以了 谢谢
