### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by qingdengyideng** [PerccyKing/batslog#7]
![image](https://user-images.githubusercontent.com/26715233/104532330-eab17880-564a-11eb-95e7-c0a9ef506003.png)

**Comment by PerccyKing** [comment]
中文乱码问题，麻烦参考一下这个试一下 https://www.cnblogs.com/lwcode6/p/11598632.html

**Comment by qingdengyideng** [comment]
可以了 谢谢

**Comment by PerccyKing** [comment]
不客气

**Comment by lazyTai** [comment]
感谢作者做出这么牛逼的插件
然后有个问题 我这个监听输出中文乱码

会不会和我的数据库连接url有关
~~~
jdbc.url= jdbc:mysql://localhost:3306/数据库名称?useUnicode=true&characterEncoding=utf-8&useSSL=false

~~~
![image](https://user-images.githubusercontent.com/16125707/118805621-b55ab700-b8d8-11eb-82a0-ac21a3befce2.png)

**Comment by PerccyKing** [comment]
> 感谢作者做出这么牛逼的插件
> 然后有个问题 我这个监听输出中文乱码
> 
> 会不会和我的数据库连接url有关
> ~~~
> jdbc.url= jdbc:mysql://localhost:3306/数据库名称?useUnicode=true&characterEncoding=utf-8&useSSL=false
> 
> ~~~
> 我的idea版本是
> ~~~
> IntelliJ IDEA 2021.1.1 (Ultimate Edition)
> Build #IU-211.7142.45, built on April 30, 2021
> ~~~
> ![image](https://user-images.githubusercontent.com/16125707/118805621-b55ab700-b8d8-11eb-82a0-ac21a3befce2.png)
> 

和数据库没有关系的，控制台输出中午正常吗？

**Comment by letianzhang** [comment]
我也有这个问题，我的IDEA版本是：IntelliJ IDEA 2021.3 (Ultimate Edition)
![image](https://user-images.githubusercontent.com/40187304/147452191-e71c4aa1-48c4-4a96-8847-d3bdd36b51e4.png)
![image](https://user-images.githubusercontent.com/40187304/147452212-b4af5c97-4871-4b15-a627-f0b998c39ff8.png)

**Comment by PerccyKing** [comment]
@letianzhang 你好，使用这个配置 https://www.cnblogs.com/lwcode6/p/11598632.html 也不可以吗？

**Comment by PerccyKing** [comment]
> 我也有这个问题，我的IDEA版本是：IntelliJ IDEA 2021.3 （Ultimate Edition） ![image](https://user-images.githubusercontent.com/40187304/147452191-e71c4aa1-48c4-4a96-8847-d3bdd36b51e4.png) ![image](https://user-images.githubusercontent.com/40187304/147452212-b4af5c97-4871-4b15-a627-f0b998c39ff8.png)

@letianzhang 还可以看看这个 https://blog.csdn.net/u010228798/article/details/93355667

**Comment by PerccyKing** [comment]
> 我也有这个问题，我的IDEA版本是：IntelliJ IDEA 2021.3 (Ultimate Edition) ![image](https://user-images.githubusercontent.com/40187304/147452191-e71c4aa1-48c4-4a96-8847-d3bdd36b51e4.png) ![image](https://user-images.githubusercontent.com/40187304/147452212-b4af5c97-4871-4b15-a627-f0b998c39ff8.png)

@letianzhang 你好，麻烦下载一下这个版本试一下看看是否乱码 [batslog-21.12.27.2232-TE.zip](https://batslog.oss-cn-shenzhen.aliyuncs.com/build/everyday/batslog-21.12.27.2232-TE.zip)

**Comment by PerccyKing** [comment]
> > 感谢作者做出这么牛逼的插件
> > 然后有个问题 我这个监听输出中文乱码
> > 会不会和我的数据库连接url有关
> > ```
> > jdbc.url= jdbc:mysql://localhost:3306/数据库名称?useUnicode=true&characterEncoding=utf-8&useSSL=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的idea版本是
> > ```
> > IntelliJ IDEA 2021.1.1 (Ultimate Edition)
> > Build #IU-211.7142.45, built on April 30, 2021
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/16125707/118805621-b55ab700-b8d8-11eb-82a0-ac21a3befce2.png)
> 
> 和数据库没有关系的，控制台输出中文正常吗？

@lazyTai 你好，麻烦下载一下这个版本试一下看看是否乱码 [batslog-21.12.27.2232-TE.zip](https://batslog.oss-cn-shenzhen.aliyuncs.com/build/everyday/batslog-21.12.27.2232-TE.zip)

**Comment by hqyxd** [comment]
控制台输出 和其他插件输出的中文都正常 只有这个插件中文是乱码  好像就今天才发现的 要怎么解决啊？

**Comment by PerccyKing** [comment]
> 控制台输出 和其他插件输出的中文都正常 只有这个插件中文是乱码  好像就今天才发现的 要怎么解决啊？

你好，插件是最新版本吗？提供一下idea的版本呢

**Comment by hqyxd** [comment]
![image](https://user-images.githubusercontent.com/30140395/153363963-217cb657-b906-46f9-93d6-fe9c29d2f714.png)
![image](https://user-images.githubusercontent.com/30140395/153364027-cd76269a-6478-49d1-a92e-6d8c99f7a1c2.png)

idea和插件的版本信息

![image](https://user-images.githubusercontent.com/30140395/153364086-1f368195-1233-4a71-b3c3-911e9aa47bc0.png)

乱码信息

**Comment by PerccyKing** [comment]
> ![image](https://user-images.githubusercontent.com/30140395/153363963-217cb657-b906-46f9-93d6-fe9c29d2f714.png)
> ![image](https://user-images.githubusercontent.com/30140395/153364027-cd76269a-6478-49d1-a92e-6d8c99f7a1c2.png)
> 
> idea和插件的版本信息
> 
> ![image](https://user-images.githubusercontent.com/30140395/153364086-1f368195-1233-4a71-b3c3-911e9aa47bc0.png)
> 
> 乱码信息

你好，这个我可能需要适配一下，我现在身边没有电脑，等我回去了就弄，麻烦耐心等待一下

**Comment by PerccyKing** [comment]
> > ![图像](https://user-images.githubusercontent.com/30140395/153363963-217cb657-b906-46f9-93d6-fe9c29d2f714.png)
> > ![图像](https://user-images.githubusercontent.com/30140395/153364027-cd76269a-6478-49d1-a92e-6d8c99f7a1c2.png)
> > idea和插件的版本信息
> > ![图像](https://user-images.githubusercontent.com/30140395/153364086-1f368195-1233-4a71-b3c3-911e9aa47bc0.png)
> > 乱码信息
> 
> 你好，这个我可能需要适配一下，我现在身边没有电脑，等我回去了就弄，麻烦耐心等待一下

你好，麻烦你 下载一下这个版本试一下，看看中文是否乱码
![image](https://user-images.githubusercontent.com/59950759/155151764-daaa422a-60f6-4c56-a814-943300c49bc9.png)

**Comment by hqyxd** [comment]
这个版本中午没有乱码

**Comment by PerccyKing** [comment]
> 这个版本中文没有乱码

你好，那麻烦你先暂时使用这个版本，乱码的问题我会尽快修复的

**Comment by PerccyKing** [comment]
> 这个版本中文没有乱码

你好，麻烦你有时间的时候，帮我试一下这个版本 ，看看是否有中文乱码的问题，十分感谢 [点击下载batslog-22.04.04.1548-TE](https://batslog.oss-cn-shenzhen.aliyuncs.com/build/everyday/batslog-22.04.04.1548-TE.zip)

**Comment by hqyxd** [comment]
暂时没有发现乱码 后面用用看看吧

**Comment by herokl** [comment]
兄弟这个中文乱码的有解决方案吗
![image](https://user-images.githubusercontent.com/85205065/186296684-a3feb2a5-244b-40cf-8b2f-e5cb09d4d49d.png)
![image](https://user-images.githubusercontent.com/85205065/186296803-197d270c-2c8c-49ab-aa6f-92e7003bd537.png)
![image](https://user-images.githubusercontent.com/85205065/186296860-3e9d71b0-fd19-43d2-aa54-80d7abd83984.png)

**Comment by herokl** [comment]
兄弟，这个中文乱码有好的解决方案希望能告知下，感谢！
![image](https://user-images.githubusercontent.com/85205065/186297131-fd977ef7-8c89-4e75-a918-d762b8f80312.png)
![image](https://user-images.githubusercontent.com/85205065/186297844-42ea8f7a-5ebf-4d55-a0e3-09861fe29246.png)
![image](https://user-images.githubusercontent.com/85205065/186297880-6cff4663-7964-47ac-9c6f-95aea08dd426.png)

**Comment by hqyxd** [comment]
> > 兄弟，这个中文乱码有好的解决方案希望能告知下，感谢！ ![图像](https://user-images.githubusercontent.com/85205065/186297131-fd977ef7-8c89-4e75-a918-d762b8f80312.png) ![图像](https://user-images.githubusercontent.com/85205065/186297844-42ea8f7a-5ebf-4d55-a0e3-09861fe29246.png) ![图像](https://user-images.githubusercontent.com/85205065/186297880-6cff4663-7964-47ac-9c6f-95aea08dd426.png)
> 
> 你好，针对于2019.2的中文问题，已经在开始优化了

最新的插件版本好像没啥问题了 idea  2020.3

**Comment by PerccyKing** [comment]
> 

是的，batslog 目前支持的最低版本就是idea2020.3

**Comment by PerccyKing** [comment]
> > 兄弟，这个中文乱码有好的解决方案希望能告知下，感谢！ ![image](https://user-images.githubusercontent.com/85205065/186297131-fd977ef7-8c89-4e75-a918-d762b8f80312.png) ![image](https://user-images.githubusercontent.com/85205065/186297844-42ea8f7a-5ebf-4d55-a0e3-09861fe29246.png) ![image](https://user-images.githubusercontent.com/85205065/186297880-6cff4663-7964-47ac-9c6f-95aea08dd426.png)
> 
> 你好，针对于2019.2的中文问题，已经在开始优化了
[batslog-22.08.27.1840-2019.2-TE.zip](https://github.com/PerccyKing/batslog/files/9437782/batslog-22.08.27.1840-2019.2-TE.zip)
你好，这个版本对2019.2做了适配，麻烦你空的时候尝试一下，期待你的反馈

**Comment by herokl** [comment]
> 

解决了，请接受我的膜拜
