### ISSUE TITLE
LocalDateTime 无法解析

### ISSUE THREAD

**Issue by liuzhihang** [PerccyKing/batslog#8]
![image](https://user-images.githubusercontent.com/26057042/110194186-2b22bb00-7e72-11eb-878a-f24c66af0604.png)

**Comment by PerccyKing** [comment]
> ![image](https://user-images.githubusercontent.com/26057042/110194186-2b22bb00-7e72-11eb-878a-f24c66af0604.png)
> 

收到，我将尽快修复

**Comment by Renzipeng** [comment]
附议 +1，建议增加可以 一行显示的功能

**Comment by PerccyKing** [comment]
@Renzipeng 请问能再明确一些吗？具体是增加显示什么呢？

**Comment by PerccyKing** [comment]
@liuzhihang 你好，这个问题，已经在新版本中修复，你可以直接下载[点击下载](https://github.com/PerccyKing/batslog/releases/download/21.03.13.1550/batslog-21.03.13.1550-Release.zip)，或者等待插件审核通过，在idea中更新使用

**Comment by PerccyKing** [comment]
@Renzipeng 你好，我明白你的意思了，这边马上做

**Comment by PerccyKing** [comment]
@Renzipeng 新功能已经发布[21.03.14.0107](https://github.com/PerccyKing/batslog/releases/download/21.03.14.0107/batslog-21.03.14.0107-Release.zip)
